version: '3.7'

services:
    nginx:
        build:
            context: .
            dockerfile: Dockerfile-nginx
        volumes:
            - ./:/var/www/symfony/
        ports:
            - 80:80
        depends_on:
            -   php
    php:
        build:
            context: .
            dockerfile: Dockerfile-php
        volumes:
            - ./:/var/www/symfony/
    phpmyadmin:
        image: phpmyadmin
        container_name: kitty_phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        ports:
            - 8080:80
        links:
            - mysql
    mysql:
        image: 'mysql:latest'
        environment:
            MYSQL_DATABASE: symfony_db
#            MYSQL_USER: symfony_user
#            MYSQL_PASSWORD: symfony_password
            MYSQL_ROOT_PASSWORD : password
        ports:
            - 3306:3306
        volumes:
            - ./database/:/var/lib/mysql/